version: '3.8'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cayena
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/data:/var/lib/mysql